version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=gophercon_user
      - POSTGRES_PASSWORD=gophercon_password
      - POSTGRES_DB=gophercon_db
    volumes:
       - golang-clean-arch-reference:/data/postgres
    ports:
      - "5432:5432"

volumes:
  golang-clean-arch-reference:
